Repository GoogleCloudPlatform/cloud-sql-proxy, pull requests merged in 2018-11, with the labels that each got.

#166 Publicly expose the driver so it can be wrapped
  proxy/dialers/postgres/hook.go
Labels: Status: Proposal, Type: Enhancement

#195 Feature/grpc connection
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
  proxy/certs/certs.go
  proxy/grpcproxy/grpc_proxy.go
  proxy/grpcproxy/proto/proxy.pb.go
  proxy/grpcproxy/proto/proxy.proto
  proxy/proxy/client.go
Labels: Type: Enhancement

#226 Don't wait as long when calling onGCE and metadata server is unavailable
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
Labels: Status: Review Needed, Type: Maintenance
