Repository GoogleCloudPlatform/cloud-sql-proxy, pull requests merged in 2018-10, with the labels that each got.

#217 Support non-service-account credential files when run as a binary
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#206 Gracefully handle TERM signals
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
  proxy/proxy/client.go
  proxy/proxy/client_test.go
Labels: Status: Review Needed, Type: Enhancement

#222 refresh SSL certs early
  proxy/proxy/client.go
  proxy/proxy/client_test.go
Labels: Priority: High, Status: Review Needed, Type: Enhancement
