Repository GoogleCloudPlatform/cloud-sql-proxy, pull requests merged in 2019-06, with the labels that each got.

#273 Add InitWithClient and deprecate InitClient because we don't want to copy Client's field sync.RWMutex by value
  proxy/proxy/dial.go
Labels: Status: Review Needed, Type: Enhancement

#285 Added the error handling of the incorrect host flag setting
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
Labels: Type: Maintenance

#289 Set custom per instance socket address
  README.md
  cmd/cloud_sql_proxy/cloud_sql_proxy.go
  cmd/cloud_sql_proxy/proxy.go
  cmd/cloud_sql_proxy/proxy_test.go
Labels: cla: yes, priority: p2, type: feature request
